version: "2"

services:
    mongodb:
        image: mongo:latest
        ports:
        - 27017:27017
        volumes:
        - /data/db
    proxy:
        image: aflatness/fec-proxy
        ports:
        - 3005:3005
    marquee:
        image: aflatness/fec-marquee:latest
        ports:
         - 3004:3004
        environment:
        - MONGOURL=mongodb://mongodb:27017/marquee
    reviews:
        image: aflatness/fec-reviews:latest
        ports:
        - 3003:3003
        environment:
        - MONGOURL=mongodb://mongodb:27017/reviews
    host-info:
        image: aflatness/fec:latest
        ports:
        - 3001:3001
        environment:
        - MONGODBURL=mongodb://mongodb:27017/fec
    related:
        image: aflatness/fec-related-info:latest
        ports:
        - 3000:3000
        environment:
        - MONGOURL=mongodb://mongodb:27017/relatedInfo